# Generated by Django 4.1.5 on 2023-01-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caloriecounter', '0002_alter_userfooditem_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfooditem',
            options={'ordering': ['-date']},
        ),
    ]
