import Head from 'next/head'
import { Button } from '@mui/material'
import MainLayout from '@/layout/MainLayout'

type Props = {
  darkMode: 'light' | 'dark'
  toggleDarkMode: () => void
}

export default function Home({ darkMode, toggleDarkMode }: Props) {
  return (
    <>
      <Head>
        <title>Caloriemeter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout darkMode={darkMode} toggleDarkMode={toggleDarkMode}>
        <div className='flex items-center m-5 space-x-3'>
          <p className='text-3xl font-bold underline text-green-500 dark:text-red-900'>Hello World!</p>
          <Button className='text-xl py-2 font-bold' variant="contained" onClick={toggleDarkMode}>{darkMode === 'light' ? 'Light' : 'Dark'}</Button>
        </div>
      </MainLayout>
    </>
  )
}
