# Generated by Django 4.1.3 on 2022-11-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Fittyfeed", "0003_userfooditem_date_alter_userfooditem_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfooditem",
            name="category",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                    ("snacks", "Snacks"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(name="Comment",),
    ]
