# Generated by Django 4.1.5 on 2023-01-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fittyfeed', '0004_alter_userfooditem_category_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfooditem',
            name='date',
            field=models.DateField(),
        ),
    ]
