import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";

type Props = {
    darkMode: 'light' | 'dark'
    toggleDarkMode: () => void
    children: React.ReactNode
}

export default function MainLayout({ children, darkMode, toggleDarkMode }: Props) {
    return (
        <>
        <Head>
            <title>Caloriemeter</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar darkMode={darkMode} toggleDarkMode={toggleDarkMode} />
        {children}
        <Footer />
        </>
    )
}